image:
  repository: artifactory.dagility.com/docker/vdcheckterraform-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdcheckterraform-backend-default.dagility.com
    paths:
    - /
serviceAccount:
  create: false
